# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#


# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod1

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Sans 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec urxvt
bindsym $mod+Shift+Return exec urxvt -e ranger
bindsym $mod+Control+Return exec "~/.config/i3/clone_terminal.sh"

# kill focused window
bindsym $mod+Shift+q kill

# disable focus mouse follow
focus_follows_mouse no

# start a program launcher
bindsym $mod+r exec rofi -show drun
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# resize with mod + keypad
set $resize_speed 8
bindsym $mod+a resize shrink width $resize_speed px or $resize_speed ppt
bindsym $mod+s resize shrink height $resize_speed px or $resize_speed ppt
bindsym $mod+d resize grow width $resize_speed px or $resize_speed ppt
bindsym $mod+w resize grow height $resize_speed px or $resize_speed ppt

# split in horizontal orientation
bindsym $mod+Shift+v split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# toggle tiling/floating
bindsym $mod+Shift+f floating toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+q layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle


# focus the parent container
bindsym $mod+p focus parent

# focus the child container
#bindsym $mod+d focus child

set $ws1 "1:"
set $ws2 "2:"
set $ws3 "3:"
#set $ws3 "3:"
set $ws4 "4:"
set $ws5 "5:"
set $ws6 "6:"
set $ws7 "7:"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# assing apps to workspaces
assign [class="Chromium"] $ws1
# assign [class="Xfce4-terminal"] $ws2
assign [class="Steam"] $ws3
assign [class="TelegramDesktop"] $ws4
assign [class="qBittorrent"] $ws5
assign [class="Eclipse"] $ws6
assign [class="jetbrains-idea"] $ws6
assign [class="Filezilla"] $ws7

# border stuff
for_window [class="^.*"] border pixel 2
hide_edge_borders both

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# applications
#bindsym $mod+

# my colors
#set $bg-color				#6d7078
#set $inactive-bg-color		#2f343f
#set $text-color			#f3f4f5
#set $inactive-text-color	#676E7D
#set $urgent-bg-color		#E53935

# background generated
set $bg-color				#0176c6
set $inactive-bg-color		#000130
set $text-color				#5ed0fd
set $inactive-text-color	#5ed0fd
set $urgent-bg-color		#ffffff

# from resources
#set_from_resource $bg-color		i3wm.color1 #6d7078
#set_from_resource $inactive-bg-color	i3wm.color2 #2f343f
#set_from_resource $text-color		i3wm.color3 #f3f4f5
#set_from_resource $inactive-text-color	i3wm.color4 #676e7d
#set_from_resource $urgent-bg-color	i3wm.color5 #e53935

# window colors
#			border			background		text			indicator
client.focused		$bg-color		$bg-color		$text-color		#00ff00
client.unfocused	$inactive-bg-color	$inactive-bg-color	$inactive-text-color	#00ff00
client.focused_inactive	$inactive-bg-color	$inactive-bg-color	$inactive-text-color	#00ff00
client.urgent		$urgent-bg-color	$urgent-bg-color	$text-color		#00ff00
client.placeholder	$bg-color		$bg-color		$text-color		#00ff00

# Media buttons
bindsym XF86AudioRaiseVolume exec --no-startup-id amixer set Master 5%+
bindsym XF86AudioLowerVolume exec --no-startup-id amixer set Master 5%-

bindsym XF86AudioMute exec --no-startup-id amixer set Master 1+ toggle
bindsym XF86AudioMicMute exec --no-startup-id amixer set Capture toggle

bindsym XF86MonBrightnessUp exec xbacklight -inc 5
bindsym XF86MonBrightnessDown exec xbacklight -dec 5

bindsym XF86TouchpadToggle exec "~/.config/i3/touchpad_toggle.sh"
#bindsym XF86TouchpadToggle exec synclient TouchpadOff=$(synclient -l | grep -c 'TouchpadOff.*=.*0')

#ThinkVantage key
#bindsym XF86Launch1

# Gaps
gaps inner 5
gaps outer 5
smart_gaps on

# Background
set $bg /usr/share/wallpapers/wp.jpg

# Init
exec_always compton -f -C -r 30
exec_always feh --bg-scale "$bg"
exec_always --no-startup-id ~/.config/i3/polybar.sh &
