set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'yuttie/comfortable-motion.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'morhetz/gruvbox'
" Plugin 'StanAngeloff/php.vim'
" Plugin 'ying17zi/vim-live-latex-preview.vim'
" Plugin 'artur-shaik/vim-javacomplete2' " Hope not to work in Java!
call vundle#end()
filetype plugin indent on
syntax on

" ycm configuration
let g:ycm_global_ycm_extra_conf = '~/.vim/ycm_extra_conf.py'
let g:ycm_server_python_interpreter = '/usr/bin/python3'
let g:ycm_key_invoke_completion = '<C-b>'
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1

" multiple file management
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>

" colors
"hi Pmenu ctermfg=NONE ctermbg=236 cterm=NONE guifg=NONE guibg=#64666d gui=NONE
"hi PmenuSel ctermfg=NONE ctermbg=24 cterm=NONE guifg=NONE guibg=#204a87 gui=NONE
"afterglow anderson angr happy_hacking gruvbox
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_italic=1
let g:gruvbox_invert_signs=1
let g:gruvbox_invert_selection=0
colorscheme gruvbox

" allow recursive searching
set path+=**

" enable powerline font integration
"let g:airline_powerline_fonts = 1
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'

" tabs
map <F3> :tabp<cr>
map <F4> :tabn<cr>
let g:airline#extensions#tabline#enabled = 1

set timeoutlen=1000
set ttimeoutlen=0
set noshowmode
set laststatus=2
set wildmenu

" hybrid line numbers
set number relativenumber

set history=200
set tabpagemax=100

" show unfinished commands
set showcmd

" # of lines from top after centering
set scrolloff=8

" auto indent
set ai

" tab
set tabstop=4
set shiftwidth=4

" word line wrap
set lbr

" lowering updatetime for gitgutter
set updatetime=100

" w!! saves any file regardless of starting vim with sudo
cmap w!! w !sudo tee > /dev/null %

" run custom scripts for various stuff
map <F5> :! ./run.sh "%"<cr>
map <F6> :! ./compile.sh "%"<cr>
map <F7> :! ./move.sh "%"<cr>

let g:Tex_DefaultTargetFormat='pdf'

" au FileType java setlocal omnifunc=javacomplete#Complete
" au FileType java map <F7> <Plug>(JavaComplete-Imports-AddMissing)
" au FileType java map <F8> <Plug>(JavaComplete-Imports-RemoveUnused)

autocmd FileType haskell setlocal expandtab " expand tabs to spaces
